---
- name: Hardening systems on the network 
  hosts: testServer
  # become: no

  vars_files:
  - checklist.yml

  roles:
  - init.logging.facts
  #- {role: filesystem, tags: [harden_level2]}
  #- sshd # redhat && debian
  #- pam
  #- system_maintenance # redhat && debian
  #- cron # redhat && debian
  - Network_Configuration # redhat && debian
  #- services
  #- filesystem
  #- system_maintenance
  #- cron
  - save.logging.facts
