---
- name: Hardening systems on the network 
  hosts: testServer
  # become: no

  vars_files:
  - checklist.yml

  roles:
  - init.logging.facts
  - sshd
  - pam
  - system_maintenance 
  - cron 
  - Network_Configuration
  - services
  - filesystem
  - filesystem.integrity.checking
  - bootloader
  - additional.process.hardening
  - warning.banners
  - update.and.patch
  - log.and.audit
  - save.logging.facts
