---
- name: Hardening systems on the network 
  hosts: testServer
  # become: no

  roles:
  #- {role: filesystem, tags: [harden_level2]}
  #- sshd # redhat && debian
  - pam
  #- system_maintenance # redhat && debian
  #- cron # redhat && debian
  #- Network_Configuration # redhat && debian