---
- name: Hardening systems on the network 
  hosts: testServer
  # become: no

  roles:
  #- {role: filesystem, tags: [harden_level2]}
  #- filesystem
  #- pam
  #- system_maintenance
  #- cron
  - Network_Configuration