---
- name: Hardening systems on the network 
  hosts: Servers
  # become: no

  vars_files:
  - checklist.yml
  - secrets.yml

  roles:
  - init.logging.facts
  #- cron
  #- services
  #- sshd
  #- system_maintenance
  #- filesystem
  #- filesystem.integrity.checking
  #- bootloader
  #- additional.process.hardening
  #- warning.banners
  #- update.and.patch
  #- log.and.audit
  - Network_Configuration
  #- pam
  - save.logging.facts
