---

- name: Ensure IP forwarding is disabled
  shell: "sysctl net.ipv4.ip_forward"
  register: grep_output
  check_mode: no
  ignore_errors: yes
  changed_when: no
  become: yes


- name: Disabling IP forwarding permanently
  register: change_state
  lineinfile:
    path: "/etc/sysctl.conf"
    regexp: 'net.ipv4.ip_forward'
    line: 'net.ipv4.ip_forward = 0'
  become: yes
  when: grep_output.stdout == "net.ipv4.ip_forward = 1" and network.disable_ip_forwarding
  

- name: Disable IP forwarding
  shell : "sysctl -w net.ipv4.ip_forward=0 && 
           sysctl -w net.ipv4.route.flush=1"
  become: yes
  when: grep_output.stdout == "net.ipv4.ip_forward = 1" and network.disable_ip_forwarding



#done
- set_fact:
    done_patch: "{{done_patch}} + ['|3.1.1| Ensure IP forwarding is disabled']" 
  when: change_state.changed and network.disable_ip_forwarding

#already done
- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|3.1.1| Ensure IP forwarding is disabled']" 
  when: not change_state.changed and network.disable_ip_forwarding

#not done
- set_fact:
    not_done: "{{not_done}} + ['|3.1.1| Ensure IP forwarding is disabled']" 
  when: not network.disable_ip_forwarding









# add default
- name: Ensure packet redirect sending is disabled
  shell: "sysctl net.ipv4.conf.all.send_redirects"
  register: grep_output
  check_mode: no
  ignore_errors: yes
  changed_when: no
  become: yes

- name: Disabling packet redirect sending permanently
  lineinfile:
    path: "/etc/sysctl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'net.ipv4.conf.all.send_redirects',  line: 'net.ipv4.conf.all.send_redirects = 0' }
    - { regexp: 'net.ipv4.conf.default.send_redirects',  line: 'net.ipv4.conf.default.send_redirects = 0' }
  when: grep_output.stdout == "net.ipv4.conf.all.send_redirects = 1" and network.disable_packet_redirect
  become: yes

- name: Disabling packet redirect sending
  shell : "sysctl -w net.ipv4.conf.all.send_redirects=0 &&
           sysctl -w net.ipv4.conf.default.send_redirects=0 &&
           sysctl -w net.ipv4.route.flush=1"
  when: grep_output.stdout == "net.ipv4.conf.all.send_redirects = 1" and network.disable_packet_redirect
  become: yes


#done
- set_fact:
    done_patch: "{{done_patch}} + ['|3.1.2| Ensure packet redirect sending is disabled']" 
  when: change_state.changed and network.disable_packet_redirect

#already done
- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|3.1.2| Ensure packet redirect sending is disabled']" 
  when: not change_state.changed and network.disable_packet_redirect

#not done
- set_fact:
    not_done: "{{not_done}} + ['|3.1.2| Ensure packet redirect sending is disabled']" 
  when: not network.disable_packet_redirect