---

- block: 
  - name: Ensure iptables is installed Debian
    apt:
      name: iptables-persistent
      update_cache: yes
    when: ansible_os_family=='Debian'


  - name: Ensure iptables is installed RedHat
    yum:
      name: iptables
      update_cache: yes
    when: ansible_os_family=='RedHat'





  - name: Ensure default deny firewall policy
    shell :  "iptables -A INPUT -p tcp --dport 22 -j ACCEPT &&
              iptables -A OUTPUT -p tcp --sport 22 -j ACCEPT &&
              iptables -P INPUT   DROP && 
              iptables -P OUTPUT  DROP &&
              iptables -P FORWARD DROP"
    when: network.configure_iptables


  - name: Ensure loopback traffic is configured
    shell : "iptables -A INPUT -i lo          -j ACCEPT && 
             iptables -A OUTPUT -o lo         -j ACCEPT &&
             iptables -A INPUT -s 127.0.0.0/8 -j DROP"
    when: network.configure_loopback_traffic



  - name: Ensure outbound and established connections are configured
    shell : "iptables -A OUTPUT -p tcp  -m state --state NEW,ESTABLISHED -j ACCEPT && 
             iptables -A OUTPUT -p udp  -m state --state NEW,ESTABLISHED -j ACCEPT &&
             iptables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT &&
             iptables -A INPUT  -p tcp  -m state --state ESTABLISHED     -j ACCEPT &&
             iptables -A INPUT  -p udp  -m state --state ESTABLISHED     -j ACCEPT &&
             iptables -A INPUT  -p icmp -m state --state ESTABLISHED     -j ACCEPT"
    when: network.configure_iptables


  - debug: msg="Please set iptables rules manually with the following command iptables -A INPUT -s <source/mask> -d <destination/mask> -p <protocol> --dport <port> -m state --state NEW -j ACCEPT"
    when: network.configure_iptables

  - set_fact:
      manual_patch: "{{manual_patch}} +  ['|3.6.5| Configure iptables rules: Please set iptables rules manually with the following command iptables -A INPUT -s <source/mask> -d <destination/mask> -p <protocol> --dport <port> -m state --state NEW -j ACCEPT']" 
      when: network.configure_iptables



  - name: saving rules v4
    shell: "iptables-save > /etc/iptables/rules.v4"
    when: network.configure_iptables and ansible_os_family=='Debian'

  # - name: saving rules v6
  #   shell: "iptables-save > /etc/iptables/rules.v6"
  #   when: network.configure_iptables and ansible_os_family=='Debian'

  - name: saving rules
    shell: "systemctl disable firewalld"
    when: network.configure_iptables and ansible_os_family=='RedHat'


  - name: Ensure iptables is installed RedHat
    yum:
      name: iptables-services
      update_cache: yes
    when: ansible_os_family=='RedHat'


  - name: Enable iptables service
    shell: "systemctl enable iptables"
    when: network.configure_iptables and ansible_os_family=='RedHat'


  - name: saving rules
    shell: "/sbin/service iptables save"
    when: network.configure_iptables and ansible_os_family=='RedHat'



  become: yes


