---

- block: 
#  - name: Ensure tcp_wrappers is installed Debian
#    apt:
#      name: tcp_wrappers
#      update_cache: yes
#    when: ansible_os_family=='Debian' and network.install_tcp_wrappers

#  - name: Ensure tcp_wrappers is installed RedHat
#    yum:
#      name: tcp_wrappers
#      update_cache: yes
#    when: ansible_os_family=='RedHat' and network.install_tcp_wrappers




  - name: Ensure /etc/hosts.allow is configured
    debug: msg='Please set hosts.allow manually like the following 
                echo "ALL <net>/<mask>, <net>/<mask>, ..." >/etc/hosts.allow
                where each <net>/<mask> combination (for example, "192.168.1.0/255.255.255.0")
                represents one network block in use by your organization that requires access to this
                system.'

  #manually
  - set_fact:
     manual_patch: "{{manual_patch}} +  ['|3.4.2| Ensure /etc/hosts.allow and /etc/hosts.deny are configured: Please set hosts.deny to ALL: ALL hosts.allow manually like the following 
                echo ALL <net>/<mask>, <net>/<mask>, ... >/etc/hosts.allow
                where each <net>/<mask> combination (for example, 192.168.1.0/255.255.255.0)
                represents one network block in use by your organization that requires access to this
                system']" 



  - name: Ensure permissions on /etc/hosts.allow are configured
    register: change_state
    file: path="/etc/hosts.allow" mode=0644 owner=root group=root

  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|3.4.4| Ensure permissions on /etc/hosts.allow are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|3.4.4| Ensure permissions on /etc/hosts.allow are configured']"
    when: not change_state.changed





  - name: Ensure permissions on /etc/hosts.deny are configured
    register: change_state
    file: path="/etc/hosts.deny" mode=0644 owner=root group=root


  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|3.4.5| Ensure permissions on /etc/hosts.deny are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|3.4.5| Ensure permissions on /etc/hosts.deny are configured']"
    when: not change_state.changed


  become: yes