---
- name: Install auditd package on Debian based distros
  apt:
    name: auditd
    state: present
    update_cache: yes

  become: yes
  when: ansible_pkg_mgr=='apt'

- name: Install auditd package on RedHat based distros
  yum: 
    name: audit
    state: present
    update_cache: yes

  become: yes
  when: ansible_pkg_mgr=='yum'


- name: Configure audit log storage size
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: 'max_log_file.+'
    line: 'max_log_file = {{max_log_file_size}}'
  become: yes


- name: Configure the system to shutdown when audit logs are full
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '\bspace_left_action.+'
    line: 'space_left_action = email'

  become: yes

- name: Configure the system to shutdown when audit logs are full
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '\baction_mail_acct.+'
    line: 'action_mail_acct = root'

  become: yes

- name: Configure the system to shutdown when audit logs are full
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '\badmin_space_left_action.+'
    line: 'admin_space_left_action = halt'

  become: yes

- name: Ensure audit logs are not automatically deleted
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '\bmax_log_file_action.+'
    line: 'max_log_file_action = keep_logs'

  become: yes

- name: Enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes
  become: yes


- name: Read /etc/default/grub file content
  shell: cat /etc/default/grub
  register: grub_cfg

- name: Enable auditing for processes that start prior to auditd
  lineinfile: 
    path: /etc/default/grub
    regexp: "(GRUB_CMDLINE_LINUX.+)([\"'])"
    line: '\1 audit=1\2'
    backrefs: yes
  become: yes
  when: grub_cfg.stdout is not search("GRUB_CMDLINE_LINUX.+audit=1")

- name: Update Grub for Debian based distros
  shell: update-grub
  become: yes
  when: ansible_os_family=='Debian'

- name: Update Grub for RedHat based distros
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  become: yes
  when: ansible_os_family=='RedHat'


# 4.1.4 ===============================================================================================================

- name: Configure auditd to collect events that modify date and time information on 64bit systems
  template:
    src: CIS.log.modify.time.date.64bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.time.date.64bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: ansible_architecture=="x86_64"

# We just need to put the right condition for 32bit systems
- name: Configure auditd to collect events that modify date and time information on 32bit systems
  template:
    src: CIS.log.modify.time.date.32bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.time.date.32bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: false

# 4.1.5 ===============================================================================================================

- name: Configure auditd to collect events that modify user/group information
  template:
    src: CIS.log.modify.user.group.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.user.group.rules
    owner: root
    group: root
    mode: 0600
  become: yes


# 4.1.6 ===============================================================================================================

- name: Configure auditd to collect events that modify the system's network environment on 64bit Debian based distros
  template:
    src: CIS.log.modify.network.debian.64bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.network.debian.64bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: ansible_architecture=='x86_64' and ansible_os_family=="Debian"

# We just need to put the right condition for 32bit systems
- name: Configure auditd to collect events that modify the system's network environment on 32bit Debian based distros
  template:
    src: CIS.log.modify.network.debian.32bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.network.debian.32bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: false and ansible_os_family=="Debian"


- name: Configure auditd to collect events that modify the system's network environment on 64bit RedHat based distros
  template:
    src: CIS.log.modify.network.redhat.64bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.network.redhat.64bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: ansible_architecture=='x86_64' and ansible_os_family=="RedHat"

# We just need to put the right condition for 32bit systems
- name: Configure auditd to collect events that modify the system's network environment on 32bit RedHat based distros
  template:
    src: CIS.log.modify.network.redhat.32bit.rules.j2
    dest: /etc/audit/rules.d/CIS.log.modify.network.redhat.32bit.rules
    owner: root
    group: root
    mode: 0600
  become: yes
  when: false and ansible_os_family=="RedHat"


# - name: Reload auditd service using systemd.
#   shell: augenrules


# - debug: msg="{{hello_world}}"