---

# 4.2.2.1 =============================================================================================================

- name: Enable syslog-ng service
  service:
    name: syslog-ng
    state: started
    enabled: yes
  become: yes


# 4.2.2.2 =============================================================================================================

- name: Configure syslog-ng logging
  blockinfile: 
    path: /etc/syslog-ng/syslog-ng.conf
    block: |
        log { source(src); source(chroots); filter(f_console); destination(console); };
        log { source(src); source(chroots); filter(f_console); destination(xconsole); };
        log { source(src); source(chroots); filter(f_newscrit); destination(newscrit); };
        log { source(src); source(chroots); filter(f_newserr); destination(newserr); };
        log { source(src); source(chroots); filter(f_newsnotice); destination(newsnotice); };
        log { source(src); source(chroots); filter(f_mailinfo); destination(mailinfo); };
        log { source(src); source(chroots); filter(f_mailwarn); destination(mailwarn); };
        log { source(src); source(chroots); filter(f_mailerr); destination(mailerr); };
        log { source(src); source(chroots); filter(f_mail); destination(mail); };
        log { source(src); source(chroots); filter(f_acpid); destination(acpid);  flags(final); };
        log { source(src); source(chroots); filter(f_acpid_full); destination(devnull); flags(final); };
        log { source(src); source(chroots); filter(f_acpid_old); destination(acpid); flags(final); };
        log { source(src); source(chroots); filter(f_netmgm); destination(netmgm); flags(final); };
        log { source(src); source(chroots); filter(f_local); destination(localmessages); };
        log { source(src); source(chroots); filter(f_messages); destination(messages); };
        log { source(src); source(chroots); filter(f_iptables); destination(firewall); };
        log { source(src); source(chroots); filter(f_warn); destination(warn); };
    create: yes
  become: yes

- name: Apply syslog-ng configurations
  shell: /usr/bin/pkill -HUP syslog-ng
  become: yes
  changed_when: false


# 4.2.2.3 =============================================================================================================

- name: Read /etc/syslog-ng/syslog-ng.conf content
  shell: cat /etc/syslog-ng/syslog-ng.conf
  register: syslog_conf_content
  changed_when: false

- name: Configure syslog-ng default log files permissions
  replace:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '(options \{[^\}]*)perm\(.*?;'
    replace: '\1perm(0640);'
  become: yes
  when: syslog_conf_content.stdout is search("perm\(\d+\)")


- name: Configure syslog-ng default log files permissions
  replace: 
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '(options \{[^\}]*\);)'
    replace: '\1 perm(0640);'
  become: yes
  when: syslog_conf_content.stdout is not search("perm\(\d+\)")


# 4.2.2.4 =============================================================================================================

- name: Configure syslog-ng to send logs to a remote log host
  debug: msg="This task should be done manually according to the site policy."


# 4.2.2.5 =============================================================================================================

- name: Configure remote syslog-ng server
  debug: msg="This task should be done manually on the remote rsyslog server."
