---

# 4.2.2.1 =============================================================================================================

- name: Enable syslog-ng service
  service:
    name: syslog-ng
    state: started
    enabled: yes
  
  register: service_result
  become: yes
  when: log.enable_syslogng

- set_fact:
    not_done: "{{not_done}} + ['|4.2.2.1| Ensure syslog-ng service is enabled']"
  when: not log.enable_syslogng

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|4.2.2.1| Ensure syslog-ng service is enabled']" 
  when: log.enable_syslogng and not service_result.changed

- set_fact:
    done_patch: "{{done_patch}} + ['|4.2.2.1| Ensure syslog-ng service is enabled']" 
  when: log.enable_syslogng and service_result.changed



# 4.2.2.2 =============================================================================================================

- block:
  - name: Configure syslog-ng logging
    template:
      dest: /etc/syslog-ng/conf.d/CIS.syslog-ng.conf
      src: CIS.syslog-ng.conf.j2 
      owner: root 
      mode: 0644 
      group: root 
    
    register: template_result
    become: yes

  - name: Apply syslog-ng configurations
    shell: /usr/bin/pkill -HUP syslog-ng
    become: yes
    changed_when: false

  when: log.config_syslogng


- set_fact:
    not_done: "{{not_done}} + ['|4.2.2.2| Ensure logging is configured']"
  when: not log.config_syslogng

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|4.2.2.2| Ensure logging is configured']" 
  when: log.config_syslogng and not template_result.changed

- set_fact:
    done_patch: "{{done_patch}} + ['|4.2.2.2| Ensure logging is configured']" 
  when: log.config_syslogng and template_result.changed


# 4.2.2.3 =============================================================================================================

- block:
  - name: Read /etc/syslog-ng/syslog-ng.conf content
    shell: cat /etc/syslog-ng/syslog-ng.conf
    register: syslog_conf_content
    changed_when: false

  - name: Configure syslog-ng default log files permissions
    replace:
      path: /etc/syslog-ng/syslog-ng.conf
      regexp: '(options \{[^\}]*)perm\(.*?;'
      replace: '\1perm(0640);'

    register: replace_result1
    become: yes
    when: syslog_conf_content.stdout is search("perm\(\d+\)")


  - name: Configure syslog-ng default log files permissions
    replace: 
      path: /etc/syslog-ng/syslog-ng.conf
      regexp: '(options \{[^\}]*\);)'
      replace: '\1 perm(0640);'

    register: replace_result2
    become: yes
    when: syslog_conf_content.stdout is not search("perm\(\d+\)")

  when: log.syslogng_file_perm


- set_fact:
    not_done: "{{not_done}} + ['|4.2.2.3| Ensure syslog-ng default file permissions configured']"
  when: not log.syslogng_file_perm

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|4.2.2.3| Ensure syslog-ng default file permissions configured']" 
  when: log.syslogng_file_perm 
        and (not replace_result1.changed and not replace_result2.changed)

- set_fact:
    done_patch: "{{done_patch}} + ['|4.2.2.3| Ensure syslog-ng default file permissions configured']" 
  when: log.syslogng_file_perm 
        and (replace_result1.changed or replace_result2.changed)


# 4.2.2.4 =============================================================================================================

- set_fact:
    manual_patch: "{{manual_patch}} + ['|4.2.2.4| Ensure syslog-ng is configured to send logs to a remote log host']" 


# 4.2.2.5 =============================================================================================================

- set_fact:
    manual_patch: "{{manual_patch}} + ['|4.2.1.5| Ensure remote syslog-ng messages are only accepted on designated log hosts']" 