---
- block:

  - name: Check if cron is running
    shell: systemctl is-enabled cron
    register: cron_state
    ignore_errors: True
    when: ansible_os_family=='Debian'

  - name: Check if cron is running
    shell: systemctl is-enabled crond
    register: cron_state
    ignore_errors: True
    when: ansible_os_family=='RedHat'


  - name: installing cron on Debian
    apt: name=cron state=latest
    when: ansible_os_family=='Debian' and 'FAILED' in cron_state.stderr


  - name: installing cron on RedHat
    yum: name=cronie state=latest
    when: ansible_os_family=='RedHat' and 'FAILED'in cron_state.stderr


  - name: Run cron on Debian
    shell: systemctl enable cron
    when: ansible_os_family=='Debian' and (cron_state.stdout == "disabled" or 'FAILED'in cron_state.stderr)

  - name: Run cron on RedHat
    shell: systemctl enable crond
    when: ansible_os_family=='RedHat' and (cron_state.stdout == "disabled" or 'FAILED'in cron_state.stderr)


  - name: Ensure permissions on /etc/crontab are configured
    file: path="/etc/crontab" owner=root group=root mode=0600 
    register: change_state

  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.2| Ensure permissions on /etc/crontab are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.2| Ensure permissions on /etc/crontab are configured']" 
    when: not change_state.changed


  - name: Ensure permissions on /etc/cron.hourly are configured
    file: path="/etc/cron.hourly" owner=root group=root mode=0700 
    register: change_state

  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.3| Ensure permissions on /etc/cron.hourly are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.3| Ensure permissions on /etc/cron.hourly are configured']" 
    when: not change_state.changed


  - name: Ensure permissions on /etc/cron.daily are configured
    file: path="/etc/cron.daily" owner=root group=root mode=0700 
    register: change_state


  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.4| Ensure permissions on /etc/cron.daily are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.4| Ensure permissions on /etc/cron.daily are configured']" 
    when: not change_state.changed

  - name: Ensure permissions on /etc/cron.weekly are configured
    file: path="/etc/cron.weekly" owner=root group=root mode=0700 
    register: change_state

  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.5| Ensure permissions on /etc/cron.weekly are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.5| Ensure permissions on /etc/cron.weekly are configured']" 
    when: not change_state.changed


  - name: Ensure permissions on /etc/cron.monthly are configured
    file: path="/etc/cron.monthly" owner=root group=root mode=0700 
    register: change_state


  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.6| Ensure permissions on /etc/cron.monthly are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.6| Ensure permissions on /etc/cron.monthly are configured']" 
    when: not change_state.changed


  - name: Ensure permissions on /etc/cron.d are configured
    file: path="/etc/cron.d" owner=root group=root mode=0700 
    register: change_state


  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.1.7| Ensure permissions on /etc/cron.d are configured']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.1.7| Ensure permissions on /etc/cron.d are configured']" 
    when: not change_state.changed


  - name: Check that the /etc/cron.allow exists
    stat:
      path: /etc/cron.allow
    register: stat_result


  - name: Create the file, if it doesnt exist already
    file:
      path: /etc/cron.allow
      state: touch
    when: stat_result.stat.exists == False 


  - name: Check that the /etc/at.allow exists
    stat:
      path: /etc/at.allow
    register: stat_result


  - name: Create the file, if it doesnt exist already
    file:
      path: /etc/at.allow
      state: touch
    when: stat_result.stat.exists == False 


  - name: Ensure permissions on /etc/cron.allow are configured
    file: path="/etc/cron.allow" owner=root group=root mode=0600
    register: change_state

  - name: Ensure permissions on /etc/at.allow are configured
    file: path="/etc/at.allow" owner=root group=root mode=0600  
    register: change_state

  - name: remove /etc/cron.deny
    file:
      state: absent
      path: "/etc/cron.deny"
    register: change_state

  - name: remove /etc/at.deny
    file:
      state: absent
      path: "/etc/at.deny"
    register: change_state


  become: yes