---

# 1.3.1 ===============================================================================================================

# Install and configure AIDE on Debian based distros
- block:
  - name: Install AIDE package on Debian based distros
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items: [aide, aide-common]
    
    register: apt_result
    tags: [print_action]
    become: yes
    when: ansible_pkg_mgr=='apt'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.3.1| Ensure AIDE is installed']" 
    when: apt_result.changed

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.3.1| Ensure AIDE is installed']" 
    when: not apt_result.changed

  # - name: Init AIDE on Debian based distros
  #   shell: aideinit

  #   tags: [print_action]
  #   become: yes

  when: ansible_os_family=="Debian" and integr_check.install_aide


- block:
  - name: Install AIDE package on RedHat based distros
    yum: 
      name: aide
      state: present
      update_cache: yes

    register: yum_result
    tags: [print_action]
    become: yes
    when: ansible_pkg_mgr=='yum'


  - set_fact:
      done_patch: "{{done_patch}} + ['|1.3.1| Ensure AIDE is installed']" 
    when: yum_result.changed

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.3.1| Ensure AIDE is installed']" 
    when: not yum_result.changed


# - name: Init AIDE on RedHat Based distros
#   shell: "aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz"

#   tags: [print_action]
#   become: yes

  when: ansible_os_family=="RedHat" and integr_check.install_aide


- set_fact:
    not_done: "{{not_done}} + ['|1.3.1| Ensure AIDE is installed']" 
  when: not integr_check.install_aide


# 1.3.2 ===============================================================================================================

- block:
  - name: Configure regular check of the filesystem on Debian based distros
    cron:
      name: Configure AIDE
      minute: 0
      hour: 5
      job: /usr/bin/aide --config /etc/aide/aide.conf --check

    register: cron_result
    tags: [print_action]
    become: yes

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.3.2| Ensure filesystem integrity is regularly checked']" 
    when: cron_result.changed

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.3.2| Ensure filesystem integrity is regularly checked']" 
    when: not cron_result.changed

  when: ansible_os_family=="Debian" and integr_check.regular_check
  
- block:
  - name: Configure regular check of the filesystem on RedHat based distros
    cron:
      name: Configure AIDE
      minute: 0
      hour: 5
      job: /usr/sbin/aide --check

    register: cron_result
    tags: [print_action]
    become: yes

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.3.2| Ensure filesystem integrity is regularly checked']" 
    when: cron_result.changed

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.3.2| Ensure filesystem integrity is regularly checked']" 
    when: not cron_result.changed

  when: ansible_os_family=="RedHat" and integr_check.regular_check

 
- set_fact:
    not_done: "{{not_done}} + ['|1.3.2| Ensure filesystem integrity is regularly checked']" 
  when: not integr_check.regular_check