# We can dispatch this file into multiple files inside the directory 01.disable.unused.filesystems if we want.
---


# 1.1.1.1 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem cramfs is not loaded
    shell: /sbin/lsmod
    register: result
    tags: [print_action]

  - block:
    - name: Disable the module cramfs
      template: src=CIS.cramfs.conf.j2 dest=/etc/modprobe.d/CIS.cramfs.conf mode=0644 owner=root
      tags: [print_action]

    - name: Disable the module cramfs
      modprobe: name=cramfs state=absent
    
    become: yes
    when: '"cramfs" in result.stdout'


  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.1| Ensure mounting of cramfs filesystems is disabled']" 
    when: '"cramfs" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.1| Ensure mounting of cramfs filesystems is disabled']" 
    when: '"cramfs" not in result.stdout'


  when: filesystem.disable_cramfs_filesystem

- set_fact:
    not_done: "{{not_done}} + ['|1.1.1.1| Ensure mounting of cramfs filesystems are disabled']"
  when: not filesystem.disable_cramfs_filesystem

# 1.1.1.2 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem freevxfs is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module freevxfs
      template: src=CIS.freevxfs.conf.j2 dest=/etc/modprobe.d/CIS.freevxfs.conf mode=0644 owner=root

    - name: Disable the module freevxfs
      modprobe: name=freevxfs state=absent
    
    become: yes
    when: '"freevxfs" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.2| Ensure mounting of freevxfs filesystems is disabled']" 
    when: '"freevxfs" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.2| Ensure mounting of freevxfs filesystems is disabled']" 
    when: '"freevxfs" not in result.stdout'

  when: filesystem.disable_freevxfs_filesystem


- set_fact:
    not_done: "{{not_done}} + ['|1.1.1.2| Ensure mounting of freevxfs filesystems are disabled']"
  when: not filesystem.disable_freevxfs_filesystem


# 1.1.1.3 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem jffs2 is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module jffs2
      template: src=CIS.jffs2.conf.j2 dest=/etc/modprobe.d/CIS.jffs2.conf mode=0644 owner=root

    - name: Disable the module jffs2
      modprobe: name=jffs2 state=absent
    
    become: yes
    when: '"jffs2" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.3| Ensure mounting of jffs2 filesystems is disabled']" 
    when: '"jffs2" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.3| Ensure mounting of jffs2 filesystems is disabled']" 
    when: '"jffs2" not in result.stdout'

  when: filesystem.disable_jffs2_filesystem


- set_fact:
    not_done: "{{not_done}} + ['|1.1.1.3| Ensure mounting of jffs2 filesystems are disabled']"
  when: not filesystem.disable_jffs2_filesystem


# 1.1.1.4 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem hfs is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module hfs
      template: src=CIS.hfs.conf.j2 dest=/etc/modprobe.d/CIS.hfs.conf mode=0644 owner=root

    - name: Disable the module hfs
      modprobe: name=hfs state=absent
    
    become: yes
    when: '"hfs" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.4| Ensure mounting of hfs filesystems is disabled']" 
    when: '"hfs" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.4| Ensure mounting of hfs filesystems is disabled']" 
    when: '"hfs" not in result.stdout'

  when: filesystem.disable_hfs_filesystem


- set_fact:
    not_done: "{{not_done}}+ ['|1.1.1.4| Ensure mounting of hfs filesystems are disabled']"
  when: not filesystem.disable_hfs_filesystem


# 1.1.1.5 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem hfsplus is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module hfsplus
      template: src=CIS.hfsplus.conf.j2 dest=/etc/modprobe.d/CIS.hfsplus.conf mode=0644 owner=root

    - name: Disable the module hfsplus
      modprobe: name=hfsplus state=absent
    
    become: yes
    when: '"hfsplus" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.5| Ensure mounting of hfsplus filesystems is disabled']" 
    when: '"hfsplus" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.5| Ensure mounting of hfsplus filesystems is disabled']" 
    when: '"hfsplus" not in result.stdout'

  when: filesystem.disable_hfsplus_filesystem


- set_fact:
    not_done: "{{not_done}}+ ['|1.1.1.5| Ensure mounting of hfsplus filesystems are disabled']"
  when: not filesystem.disable_hfsplus_filesystem


# 1.1.1.6 =============================================================================================================
  
- block:
  - name: Verify that the module for the filesystem squashfs is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module squashfs
      template: src=CIS.squashfs.conf.j2 dest=/etc/modprobe.d/CIS.squashfs.conf mode=0644 owner=root

    - name: Disable the module squashfs
      modprobe: name=squashfs state=absent
    
    become: yes
    when: '"squashfs" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.6| Ensure mounting of squashfs filesystems is disabled']" 
    when: '"squashfs" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.6| Ensure mounting of squashfs filesystems is disabled']" 
    when: '"squashfs" not in result.stdout'

  when: filesystem.disable_squashfs_filesystem


- set_fact:
    not_done: "{{not_done}}+ ['|1.1.1.6| Ensure mounting of squashfs filesystems are disabled']"
  when: not filesystem.disable_squashfs_filesystem


# 1.1.1.7 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem udf is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module udf
      template: src=CIS.udf.conf.j2 dest=/etc/modprobe.d/CIS.udf.conf mode=0644 owner=root

    - name: Disable the module udf
      modprobe: name=udf state=absent
    
    become: yes
    when: '"udf" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.7| Ensure mounting of udf filesystems is disabled']" 
    when: '"udf" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.7| Ensure mounting of udf filesystems is disabled']" 
    when: '"udf" not in result.stdout'
 
  when: filesystem.disable_udf_filesystem


- set_fact:
    not_done: "{{not_done}}+ ['|1.1.1.7| Ensure mounting of udf filesystems are disabled']"
  when: not filesystem.disable_udf_filesystem


# 1.1.1.8 =============================================================================================================

- block:
  - name: Verify that the module for the filesystem vfat is not loaded
    shell: /sbin/lsmod
    register: result

  - block:
    - name: Disable the module vfat
      template: src=CIS.vfat.conf.j2 dest=/etc/modprobe.d/CIS.vfat.conf mode=0644 owner=root

    - name: Disable the module vfat
      modprobe: name=vfat state=absent
    
    become: yes
    tags: [harden_server_level2, harden_workstation_level2]
    when: '"vfat" in result.stdout'

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.1.8| Ensure mounting of vfat filesystems is disabled']" 
    when: '"vfat" in result.stdout'

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.1.8| Ensure mounting of vfat filesystems is disabled']" 
    when: '"vfat" not in result.stdout'

  when: filesystem.disable_vfat_filesystem


- set_fact:
    not_done: "{{not_done}}+ ['|1.1.1.8| Ensure mounting of vfat filesystems are disabled']"
  when: not filesystem.disable_vfat_filesystem