---

# 1.1.2 ===============================================================================================================

- name: Verify that a separate partition exists for /tmp
  set_fact:
    tmp_partition: "{{item}}"
  with_items: "{{ansible_mounts}}"
  when: "item.mount=='/tmp'"
  no_log: yes


# Set the wanted paramaters into a variable.
- block:
  - name: Setting the parameter nodev
    set_fact:
      mount_options: "nodev"
    when: filesystem.tmp_partition_nodev

  - name: Setting the parameter nosuid
    set_fact:
      mount_options: "{{ 'nosuid' if mount_options is not defined else mount_options + ',' + 'nosuid' }}"
    when: filesystem.tmp_partition_nosuid

  - name: Setting the parameter noexec
    set_fact:
      mount_options: "{{ 'noexec' if mount_options is not defined else mount_options + ',' + 'noexec' }}"
    when: filesystem.tmp_partition_noexec

  - name: Setting extra parameters
    set_fact:
      mount_options: "{{ 'rw,relatime' if mount_options is not defined else 'rw,' + mount_options + ',relatime' }}"


# Create a hardened tmp partition
- block: 
  # - name: Create an image file for the tmp partition (This may take a while)
  - name: Create a the tmp partition
    shell: /bin/dd if=/dev/zero of=/tmp_partition.bin bs=512 count=2097152
    tags: [print_action]

  - name: Create an ext4 filesystem on the new created tmp partition
    filesystem: 
      fstype: ext4
      dev: /tmp_partition.bin

  - name: Change the image file permissions
    file: dest=/tmp_partition.bin mode=660

  - name: Mount the new created tmp partition
    mount: 
      path: /tmp
      src: /tmp_partition.bin
      fstype: ext4
      opts: "{{mount_options}}"
      state: mounted

  - name: Changing the tmp folder permissions
    file: dest=/tmp mode=1777

  when: tmp_partition is not defined and 
        filesystem.tmp_partition_create
  become: yes
  tags: [harden_server_level2, harden_workstation_level2]

- block:
  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.2| Ensure separate partition exists for /tmp']" 


  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.3| Ensure nodev option set on /tmp partition']" 
    when: filesystem.tmp_partition_nodev

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.3| Ensure nodev option set on /tmp partition']" 
    when: not filesystem.tmp_partition_nodev


  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']" 
    when: filesystem.tmp_partition_nosuid

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']" 
    when: not filesystem.tmp_partition_nosuid


  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.5| Ensure noexec option set on /tmp partition']" 
    when: filesystem.tmp_partition_noexec

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.5| Ensure noexec option set on /tmp partition']" 
    when: not filesystem.tmp_partition_noexec

  when: tmp_partition is not defined and
        filesystem.tmp_partition_create

- block:
  - set_fact:
      not_done: "{{not_done}} + ['|1.1.2| Ensure separate partition exists for /tmp']" 

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.3| Ensure nodev option set on /tmp partition']" 

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']" 

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.5| Ensure noexec option set on /tmp partition']" 

  when: tmp_partition is not defined and
        not filesystem.tmp_partition_create



# Harden the tmp partition if it already exists
- block:
  - name: Find the device of the tmp partition
    shell: losetup --list -O BACK-FILE "{{tmp_partition.device}}"
    register: losetup_result
    when: "'/dev/loop' in tmp_partition.device"
    changed_when: false

  - name: Find the device of the tmp partition
    set_fact:
      tmp_device: "{{losetup_result.stdout_lines[1]}}"
    when: "'/dev/loop' in tmp_partition.device"

  - name: Find the device of the tmp partition
    set_fact:
      tmp_device: "{{tmp_partition.device}}"
    when: "'/dev/loop' not in tmp_partition.device"

  - name: Remount the tmp partition with the proper options
    mount: 
      path: /tmp
      src: "{{tmp_device}}"
      fstype: "{{tmp_partition.fstype}}"
      opts: "{{mount_options}}"
      state: mounted
    tags: [print_action]

  when: tmp_partition is defined 
        # and ("nosuid" not in tmp_partition.options 
        # or "nodev" not in tmp_partition.options
        # or "noexec" not in tmp_partition.options)
  become: yes


- block:
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.2| Ensure separate partition exists for /tmp']" 


  - set_fact:
      not_done: "{{not_done}} + ['|1.1.3| Ensure nodev option set on /tmp partition']"
    when: not filesystem.tmp_partition_nodev

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.3| Ensure nodev option set on /tmp partition']" 
    when: "filesystem.tmp_partition_nodev and 'nodev' in tmp_partition.options"

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.3| Ensure nodev option set on /tmp partition']" 
    when: "filesystem.tmp_partition_nodev and 'nodev' not in tmp_partition.options"


  - set_fact:
      not_done: "{{not_done}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']"
    when: not filesystem.tmp_partition_nosuid

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']" 
    when: "filesystem.tmp_partition_nosuid and 'nosuid' in tmp_partition.options"

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.4| Ensure nosuid option set on /tmp partition']" 
    when: "filesystem.tmp_partition_nosuid and 'nosuid' not in tmp_partition.options"
  

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.5| Ensure noexec option set on /tmp partition']"
    when: not filesystem.tmp_partition_noexec

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.5| Ensure noexec option set on /tmp partition']" 
    when: "filesystem.tmp_partition_noexec and 'noexec' in tmp_partition.options"

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.5| Ensure noexec option set on /tmp partition']" 
    when: "filesystem.tmp_partition_noexec and 'noexec' not in tmp_partition.options"
  
  when: tmp_partition is defined
