---

# 1.1.5 ===============================================================================================================

- name: Verify that a separate partition exists for /var
  set_fact:
    var_partition: "{{item}}"
  with_items: "{{ansible_mounts}}"
  when: "item.mount=='/var'"
  no_log: yes


- set_fact:
    manual_patch: "{{manual_patch}} + ['|1.1.5| Ensure separate partition exists for /var']" 
  when: var_partition is not defined

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|1.1.5| Ensure separate partition exists for /var']" 
  when: var_partition is defined