---

# 1.1.10 ==============================================================================================================

- name: Verify that a separate partition exists for /var/log
  set_fact:
    var_log_partition: "{{item}}"
  with_items: "{{ansible_mounts}}"
  when: "item.mount=='/var/log'"
  no_log: yes


- set_fact:
    manual_patch: "{{manual_patch}} + ['|1.1.11| Ensure separate partition exists for /var/log']" 
  when: var_log_partition is not defined

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|1.1.11| Ensure separate partition exists for /var/log']" 
  when: var_log_partition is defined
