--- 
- name: Verify that a separate partition exists for /var/log/audit
  set_fact:
    var_log_audit_partition: "{{item}}"
  with_items: "{{ansible_mounts}}"
  when: "item.mount=='/var/log/audit'"
  no_log: yes


- set_fact:
    manual_patch: "{{manual_patch}} + ['|1.1.12| Ensure separate partition exists for /var/log/audit']" 
  when: var_log_audit_partiton is not defined

- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|1.1.12| Ensure separate partition exists for /var/log/audit']" 
  when: var_log_audit_partiton is defined