# Not tested yet
---

# 1.1.13 ==============================================================================================================

- name: Verify that a separate partition exists for /home
  set_fact:
    home_partition: "{{item}}"
  with_items: "{{ansible_mounts}}"
  when: "item.mount=='/home'"
  no_log: yes


- set_fact:
    manual_patch: "{{manual_patch}} + ['|1.1.13| Ensure separate partition exists for /home']" 
  when: home_partition is not defined


# 1.1.14 ==============================================================================================================

- name: Remount the /home partition with the proper options
  mount: 
    path: /home
    src: "{{home_partition.device}}"
    fstype: "{{home_partition.fstype}}"
    opts: rw,{{ 'nodev,' if filesystem.home_partition_nodev else '' }}relatime
    state: mounted
  when: home_partition is defined 
  tags: [print_action]

- block:
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.13| Ensure separate partition exists for /home']" 

  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|1.1.14| Ensure nodev option set on /home partition']" 
    when: "filesystem.home_partition_nodev and 'nodev' in home_partition.options"

  - set_fact:
      done_patch: "{{done_patch}} + ['|1.1.14| Ensure nodev option set on /home partition']" 
    when: "filesystem.home_partition_nodev and 'nodev' not in home_partition.options"

  - set_fact:
      not_done: "{{not_done}} + ['|1.1.14| Ensure nodev option set on /home partition']" 
    when: not filesystem.home_partition_nodev

  when: home_partition is defined