---
- name: Detect if the /dev/shm partition has the right options
  shell: mount
  register: mount_output

- name: Remount the /dev/shm partition with the proper options And these options to boot
  mount: 
    path: /dev/shm
    src: /dev/shm
    fstype: tmpfs
    opts: rw,nosuid,noexec,nodev,relatime
    state: mounted

  when: mount_output.stdout is not search("/dev/shm.*noexec")
      or mount_output.stdout is not search("/dev/shm.*nodev")
      or mount_output.stdout is not search("/dev/shm.*nosuid")

  become: yes