---

- name: Install libpam-pwquality.
  apt: name=libpam-pwquality state=latest
  become: yes


- name: Allow 3 tries before sending back a failure.
  lineinfile:
    path: "/etc/pam.d/common-password"
    regexp: "pam_pwquality.so"
    line: 'password requisite pam_pwquality.so retry=3'
  become: yes


- name: Set password policy by default to >
            password lenght >= 14
            must provide at least one digit
            must provide at least one uppercase character
            must provide at least one special character
            must provide at least one lowercase character
            change variables to meet your company password policy please
  lineinfile:
    path: "/etc/pam.d/common-password"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^minlen',  line: 'minlen = 14' }
    - { regexp: '^dcredit', line: 'dcredit = -1' }
    - { regexp: '^lcredit', line: 'lcredit = -1' }
    - { regexp: '^ocredit', line: 'ocredit = -1' }
    - { regexp: '^ucredit', line: 'ucredit = -1' }
  become: yes
