---
# to unlock a blocked user run
#/sbin/pam_tally2 -u <username> --reset
- name: configure lockout for failed password attempts, unlock after 900 seconds
  lineinfile:
    path: "/etc/pam.d/common-auth"
    regexp: 'pam_tally2.so'
    line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'
  become: yes