---

- name: set password reuse limite and password hashing algorithm to SHA512 Debian
  lineinfile:
    path: "/etc/pam.d/common-password"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
    - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password [success=1 default=ignore] pam_unix.so sha512' }
  become: yes
  when: ansible_os_family=='Debian' and password_reuse_limit_and_sha512_as_default

  
- name: set password reuse limite and password hashing algorithm to SHA512 RedHat
  lineinfile:
    path: "/etc/pam.d/password-auth"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
    - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password required pam_unix.so sha512' }
  become: yes
  when: ansible_os_family=='RedHat' and password_reuse_limit_and_sha512_as_default


- name: set password reuse limite and password hashing algorithm to SHA512 RedHat
  lineinfile:
    path: "/etc/pam.d/system-auth"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
    - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password required pam_unix.so sha512' }
  become: yes
  when: ansible_os_family=='RedHat' and password_reuse_limit_and_sha512_as_default

  