---

- name: set password reuse limite and password hashing algorithm to SHA512
  lineinfile:
    path: "/etc/pam.d/common-password"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
    - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password [success=1 default=ignore] pam_unix.so sha512' }
  become: yes



  