---
- block:
  - name: set password reuse limite and password hashing algorithm to SHA512 Debian
    lineinfile:
      path: "/etc/pam.d/common-password"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
      - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password [success=1 default=ignore] pam_unix.so sha512' }
    register: change_state
    become: yes
    when: ansible_os_family=='Debian'

    
  - name: set password reuse limite and password hashing algorithm to SHA512 RedHat
    lineinfile:
      path: "/etc/pam.d/password-auth"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
      - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password required pam_unix.so sha512' }
    register: change_state
    become: yes
    when: ansible_os_family=='RedHat'


  - name: set password reuse limite and password hashing algorithm to SHA512 RedHat
    lineinfile:
      path: "/etc/pam.d/system-auth"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^password\s+required\s+pam_pwhistory.so',  line: 'password required pam_pwhistory.so remember=5' }
      - { regexp: '^.*?\bpassword\b.*?\bpam_unix\b.*?$',  line: 'password required pam_unix.so sha512' }
    register: change_state
    become: yes
    when: ansible_os_family=='RedHat'

  #done
  - set_fact:
      done_patch: "{{done_patch}} + ['|5.3.3| Ensure password reuse is limited and sha512 as default hashing algorithm']" 
    when: change_state.changed

  #already done
  - set_fact:
      already_done_patch: "{{already_done_patch}} + ['|5.3.3| Ensure password reuse is limited and sha512 as default hashing algorithm']" 
    when: not change_state.changed
     
  when: pam.password_reuse_limit_and_sha512_as_default

#not done
- set_fact:
    not_done: "{{not_done}} + ['|5.3.3| Ensure password reuse is limited and sha512 as default hashing algorithm']" 
  when: not pam.password_reuse_limit_and_sha512_as_default