---
- block:
  - name: Harden '/boot/grub/grub.cfg' permissions and ownership
    file:
      path: "/boot/grub/grub.cfg"
      owner: "root"
      group: "root"
      mode: 0400
    become: yes


  - name: Protect the bootloader with a password
    debug: msg="It is too dangerous to set a password for the bootloader automatically from here,
        You should manually log into that machine and perform the operation. 
        A script will be generated that will let you protect the bootloader with a password when you log 
        to the machine."

  - name: Require authentication for single user mode
    debug: msg="It is too dangerous to set the root user password from here,
        You should manually log into that machine and perform the operation. 
        A script will be generated that will let you create the root user password when you log 
        to the machine."

  when: ansible_distribution=="Ubuntu"

