---

- block: 
  - name: Ensure time synchronization is in use install ntp
    yum:
      name: ntp
      update_cache: yes

  - name: Ensure time synchronization is in use install chrony
    yum:
      name: chrony
      update_cache: yes
    
  become: yes
  when: ansible_os_family=='RedHat'



- block: 
  - name: Ensure time synchronization is in use install ntp
    apt:
      name: ntp
      update_cache: yes

  - name: Ensure time synchronization is in use install chrony
    apt:
      name: chrony
      update_cache: yes
    
  become: yes
  when: ansible_os_family=='Debian'





- name: Ensure ntp is configured
  lineinfile:
    path:   "/etc/ntp.conf"
    regexp: "{{item.regexp}}"
    line:   "{{item.line}}"
  with_items:
    - { regexp: 'restrict -4 default kod nomodify notrap nopeer noquery',  line: 'restrict -4 default kod nomodify notrap nopeer noquery' }
    - { regexp: 'restrict -6 default kod nomodify notrap nopeer noquery',  line: 'restrict -6 default kod nomodify notrap nopeer noquery' }
  register: change_state_1
  become: yes
  when: services.configure_ntp

- name: Ensure ntp is configured
  lineinfile:
    path: "/etc/init.d/ntp"
    regexp: 'RUNASUSER'
    line: 'RUNASUSER=ntp' 
  register: change_state_2_debian
  become: yes
  when: services.configure_ntp and ansible_os_family=='Debian'

- name: Ensure ntp is configured
  lineinfile:
    path: "/etc/sysconfig/ntpd"
    regexp: 'OPTIONS='
    line: 'OPTIONS="-u ntp:ntp"' 
  register: change_state_2_redhat
  become: yes
  when: services.configure_ntp and ansible_os_family=='RedHat'

#done
- set_fact:
    done_patch: "{{done_patch}} + ['|2.2.1.2| Ensure ntp is configured']" 
  when: change_state_1.changed or change_state_2_debian.changed or change_state_2_redhat.changed and services.configure_ntp

#already done
- set_fact:
    already_done_patch: "{{already_done_patch}} + ['|2.2.1.2| Ensure ntp is configured']" 
  when: not change_state_1.changed or not change_state_2.changed and services.configure_ntp

#not done
- set_fact:
    not_done: "{{not_done}} + ['|2.2.1.2| Ensure ntp is configured']" 
  when: not services.configure_ntp


- debug: msg="Please configure a server NTP by running the following command manually $ server <remote-server>"
  when: services.configure_ntp


#manually
- set_fact:
    manual_patch: "{{manual_patch}} +  ['|2.2.1.2| Ensure chrony is configured: Please configure a server NTP by running the following command manually $ server <remote-server>']" 
  when: services.configure_ntp







- debug: msg="Please configure a server for chrony by running the following command manually $ server <remote-server>"
  when: services.configure_chrony


#manually
- set_fact:
    manual_patch: "{{manual_patch}} +  ['|2.2.1.3| Ensure chrony is configured: Please configure a server by running the following command manually server <remote-server>']" 
  when: services.configure_chrony














