---
- block:
  - stat:
      path: "{{sshd_config_path}}"
    register: sshd_config

  - name: Wrong permissions on sshd_config
    file: path="{{sshd_config_path}}" mode=0600
    when: sshd_config.stat.mode != '0600'

  - name: Wrong ownership on sshd_config
    file: path="{{sshd_config_path}}" owner=root group=root
    when: sshd_config.stat.pw_name != 'root' or sshd_config.stat.gr_name != 'root'


  - name: set protocol version == 2
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^Protocol'
      line: 'Protocol 2'


  - name: set LogLevel == INFO
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^LogLevel'
      line: 'LogLevel INFO'


  - name: set X11 forwarding == disabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^X11Forwarding'
      line: 'X11Forwarding no'

  # set it to be variable
  - name: set MaxAuthTries == 4
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^MaxAuthTries'
      line: 'MaxAuthTries 4'

  - name: set IgnoreRhosts == enabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^IgnoreRhosts'
      line: 'IgnoreRhosts yes'


  - name: set HostbasedAuthentication == disabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^HostbasedAuthentication'
      line: 'HostbasedAuthentication no'


  - name: set root login == enabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'


  - name: set PermitEmptyPasswords == disabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'


  - name: set PermitUserEnvironment == disabled
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: 'PermitUserEnvironment'
      line: 'PermitUserEnvironment no'


  - name: Ensure only approved MAC algorithms are used
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: 'MACs'
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-
  etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'


  - name: set ClientAliveInterval == 300 and set ClientAliveCountMax == 4 
    lineinfile:
      path:   "{{sshd_config_path}}"
      regexp: "{{item.regexp}}"
      line:   "{{item.line}}"
    with_items:
      - { regexp: '^ClientAliveInterval',  line: 'ClientAliveInterval 300' }
      - { regexp: '^ClientAliveCountMax',  line: 'ClientAliveCountMax 4' }


  - name: Ensure SSH LoginGraceTime is set to one minute or less
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^LoginGraceTime'
      line: 'LoginGraceTime 60' 
      

  - name: Ensure SSH warning banner is configured
    lineinfile:
      path: "{{sshd_config_path}}"
      regexp: '^Banner'
      line: 'Banner /etc/issue.net'  
      
  become: yes